---
name: 'install-packwiz'
description: 'Install the Packwiz binary'
author: 'actionhippie'

runs:
  using: 'composite'

  steps:
    - name: Download latest binary
      shell: bash
      run: |
        curl -sSLo packwiz https://dl.webhippie.de/minecraft/packwiz/20240325/packwiz-linux-amd64 && \
          chmod +x packwiz && \
          sudo mv packwiz /usr/local/bin/

...
