---
# yaml-language-server: $schema=https://www.schemastore.org/github-action.json
name: 'install-packwiz'
description: 'Install the Packwiz binary'
author: 'actionhippie'
branding:
  icon: award
  color: green

runs:
  using: 'composite'

  steps:
    - name: Download latest binary
      shell: bash
      run: |
        curl -sSLo packwiz.zip https://nightly.link/packwiz/packwiz/workflows/go/main/Linux%2064-bit%20x86.zip && \
          unzip packwiz.zip && \
          chmod +x packwiz && \
          sudo mv packwiz /usr/local/bin/ && \
          rm packwiz.zip

...
